### ISSUE TITLE
Getting blank green screen

### ISSUE THREAD

**Issue by chapeter** [amney/confexplorer#3]
Tried to connect to two different aci fabrics from multiple servers...nothing seems to be getting populated.  Just see a green screen with a box that says Object Info.  Tried browsers: Chrome, Firefox, and Safari

**Comment by amney** [comment]
Hey Chad - can you let me know if this works now? There was an issue with the authentication with the APIC. Also added a loading spinner to let the user know something is happening :)

**Comment by chapeter** [comment]
Works great now.  Very interesting way of looking at the config.  Kinda need to see which elements are configured where

Got it added into my my aci demo environment, and to my scripts to build the environment:
http://github.com/chapeter/acitoolkitapps
http://github.com/chapeter/acitoolkitapps-build
